In [21]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [8]:
data = load_iris()
X=data.data
y=data.target

In [62]:
label=data.target_names
label

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
type(X)

numpy.ndarray

In [11]:
type(y)

numpy.ndarray

In [14]:
len(y)

150

In [20]:
(unique, counts) = np.unique(y, return_counts=True)
frequencies = np.asarray((unique, counts)).T
print(frequencies)

[[ 0 50]
 [ 1 50]
 [ 2 50]]


In [22]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2,random_state=5)

In [26]:
X_train.shape

(120, 4)

In [27]:
X_test.shape

(30, 4)

In [57]:
lr=LogisticRegression()
lr.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [29]:
lr.score(X_train,Y_train)

0.9583333333333334

In [30]:
lr.predict(X_test)

array([1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2,
       0, 1, 1, 2, 1, 1, 1, 2])

In [32]:
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB 
from sklearn.ensemble import RandomForestClassifier
from mlxtend.classifier import StackingClassifier
from xgboost import XGBClassifier
import numpy as np
import warnings

warnings.simplefilter('ignore')

clf1 = KNeighborsClassifier(n_neighbors=1)
clf2 = RandomForestClassifier(random_state=1)
clf3 = GaussianNB()
lr = LogisticRegression()
sclf = StackingClassifier(classifiers=[clf1, clf2, clf3], 
                          meta_classifier=lr)
xg=XGBClassifier()

print('3-fold cross validation:\n')

for clf, label in zip([clf1, clf2, clf3, sclf,xg], 
                      ['KNN', 
                       'Random Forest', 
                       'Naive Bayes',
                       'StackingClassifier','XGB']):

    scores = model_selection.cross_val_score(clf, X_train, Y_train, 
                                              cv=10, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" 
          % (scores.mean(), scores.std(), label))

3-fold cross validation:

Accuracy: 0.97 (+/- 0.04) [KNN]
Accuracy: 0.97 (+/- 0.04) [Random Forest]
Accuracy: 0.97 (+/- 0.04) [Naive Bayes]
Accuracy: 0.97 (+/- 0.04) [StackingClassifier]
Accuracy: 0.97 (+/- 0.04) [XGB]


In [37]:
SVC_Model=SVC(probability=True)
SVC_Model.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=True, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [66]:
scores = model_selection.cross_val_score(SVC_Model, X_train, Y_train,cv=10, scoring='accuracy')
print("Accuracy: %0.5f (+/- %0.2f) [%s]"% (scores.mean(), scores.std(), label))

Accuracy: 0.98333 (+/- 0.03) [['setosa' 'versicolor' 'virginica']]


In [40]:
SVC_Model.score(X_train,Y_train)

0.9916666666666667

In [59]:
pred=SVC_Model.predict(X_test)
pred

array([1, 2, 2, 0, 2, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2,
       0, 1, 1, 2, 1, 1, 1, 2])

In [43]:
Y_test

array([1, 2, 2, 0, 2, 1, 0, 1, 0, 1, 1, 2, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2,
       0, 1, 1, 2, 1, 1, 1, 2])

In [48]:
np.max(SVC_Model.predict_proba(X_test),axis=1).shape

(30,)

In [64]:
label[pred]

array(['versicolor', 'virginica', 'virginica', 'setosa', 'virginica',
       'versicolor', 'setosa', 'virginica', 'setosa', 'versicolor',
       'versicolor', 'virginica', 'virginica', 'virginica', 'setosa',
       'setosa', 'virginica', 'virginica', 'setosa', 'setosa',
       'versicolor', 'virginica', 'setosa', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'versicolor', 'virginica'],
      dtype='<U10')

In [54]:
np.concatenate([pred.reshape(-1,1),np.max(SVC_Model.predict_proba(X_test),axis=1).reshape(-1,1)],axis=1)

array([[1.        , 0.9881527 ],
       [2.        , 0.91689922],
       [2.        , 0.98238323],
       [0.        , 0.95793752],
       [2.        , 0.97832003],
       [1.        , 0.93894438],
       [0.        , 0.96334502],
       [2.        , 0.6218673 ],
       [0.        , 0.9550199 ],
       [1.        , 0.80309687],
       [1.        , 0.87188701],
       [2.        , 0.5149602 ],
       [2.        , 0.98285678],
       [2.        , 0.97533079],
       [0.        , 0.95959   ],
       [0.        , 0.94762669],
       [2.        , 0.68608218],
       [2.        , 0.97411038],
       [0.        , 0.96349614],
       [0.        , 0.96329281],
       [1.        , 0.98824707],
       [2.        , 0.98476615],
       [0.        , 0.96377361],
       [1.        , 0.68838391],
       [1.        , 0.97983364],
       [2.        , 0.97915861],
       [1.        , 0.9857628 ],
       [1.        , 0.98020211],
       [1.        , 0.92273486],
       [2.        , 0.98546714]])

In [ ]:
import torch
import torch.nn as nn

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

clfs = []
clfs.append(LogisticRegression())
clfs.append(SVC(probability=True))
clfs.append(SVC())
clfs.append(KNeighborsClassifier(n_neighbors=3))
clfs.append(DecisionTreeClassifier())
clfs.append(RandomForestClassifier())
clfs.append(GradientBoostingClassifier())
clfs.append(XGBClassifier())


for classifier in clfs:
    scores = cross_validate(classifier, X_train, Y_train)
    print('---------------------------------')
    print(str(classifier))
    print('-----------------------------------')
    for key, values in scores.items():
            print(key,' mean ', values.mean())
            print(key,' std ', values.std())

---------------------------------
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)
-----------------------------------
fit_time  mean  0.0013333956400553386
fit_time  std  0.0018857061981754134
score_time  mean  0.0
score_time  std  0.0
test_score  mean  0.9500000000000001
test_score  std  0.035355339059327355
train_score  mean  0.9583333333333334
train_score  std  0.005892556509887928
---------------------------------
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=True, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
-----------------------------------
fit_time  mean  0.0040005842844645185
fit_time  std  1.5734823444067107e-06
score_time  mea

In [67]:
SVC_Model.score(X_test,Y_test)

0.9666666666666667